const profiles = [
  {
    name: 'Ray Simar',
    avatar: '/assets/Ray.jpeg',
    title: 'Professor in the Practice',
    organization: 'Department of ECE at Rice University',
    roles: ['Project Inspiration', 'Project Advisor'],
    link: 'https://profiles.rice.edu/faculty/ray-simar',
  },
  {
    name: 'I-No Liao',
    avatar: '/assets/ino-liao.jpeg',
    title: 'Master of Computer Science Student',
    organization: 'Rice University',
    roles: ['Web Dev', 'COVID-19 Data', 'Tableau UI'],
    link: 'https://inoliao.info/',
  },
  {
    name: 'Vinicius Da Silva',
    avatar: '/assets/vini-da-silva.jpeg',
    title: 'PhD Candidate',
    organization: 'Rice University',
    roles: ['COVID-19 Data', 'Network Modeling'],
    link: 'https://www.linkedin.com/in/vini-goncalves/',
  },
  {
    name: 'Chang-Yuan Shih',
    avatar: '/assets/defaultAvatar.png',
    title: '',
    organization: 'Rice University',
    roles: [],
    link: '',
  },
  {
    name: 'Howard Wang',
    avatar: '/assets/defaultAvatar.png',
    title: '',
    organization: 'Rice University',
    roles: [],
    link: '',
  },
  {
    name: 'Chiao-Yu Pai',
    avatar: '/assets/defaultAvatar.png',
    title: '',
    organization: 'Rice University',
    roles: [],
    link: '',
  },
  {
    name: 'Yu-Che Cheng',
    avatar: '/assets/defaultAvatar.png',
    title: '',
    organization: 'Rice University',
    roles: [],
    link: '',
  },
  {
    name: 'Nicolae Sapoval',
    avatar: '/assets/nicolae-sapoval.jpeg',
    title: 'PhD Student',
    organization: 'Rice University',
    roles: ['Bioinformatics'],
    link: 'https://nsapoval.com',
  },
  {
    name: 'Xiaotong Lu',
    avatar: '/assets/defaultAvatar.png',
    title: '',
    organization: 'Rice University',
    roles: [],
    link: '',
  },
  {
    name: 'Qi Wang',
    avatar: '/assets/defaultAvatar.png',
    title: '',
    organization: 'Rice University',
    roles: [],
    link: '',
  },
  {
    name: 'Wei Xia',
    avatar: '/assets/defaultAvatar.png',
    title: '',
    organization: 'Rice University',
    roles: [],
    link: '',
  },
  {
    name: 'Xuyang Xiao',
    avatar: '/assets/defaultAvatar.png',
    title: '',
    organization: 'Rice University',
    roles: [],
    link: '',
  },
  {
    name: 'Wenlong Yan',
    avatar: '/assets/defaultAvatar.png',
    title: '',
    organization: 'Rice University',
    roles: [],
    link: '',
  },
];

export default profiles;
