const profiles = [
  {
    name: 'Ray Simar',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
  {
    name: 'I-No Liao',
    avatar: '/assets/ino-liao.jpeg',
    title: 'MCS Student at Rice University',
    details: 'Web Development | COVID-19 Data | Tableau Viz',
    link: 'https://inoliao.info/',
  },
  {
    name: 'Chang-Yuan Shih',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
  {
    name: 'Chiao-Yu Pai',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
  {
    name: 'Howard Wang',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
  {
    name: 'Vinicius Da Silva',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
  {
    name: 'Yu-Che Cheng',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
  {
    name: 'Nicolae Sapoval',
    avatar: '/assets/nicolae-sapoval.jpeg',
    title: 'PhD Student at Rice University',
    details: 'Bioinformatics',
    link: 'https://nsapoval.com',
  },
  {
    name: 'Xiaotong Lu',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
  {
    name: 'Qi Wang',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
  {
    name: 'Wei Xia',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
  {
    name: 'Xuyang Xiao',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
  {
    name: 'Wenlong Yan',
    avatar: '/assets/defaultAvatar.png',
    title: 'Your Title at Rice University',
    details: 'Your contributions to this project',
    link: '',
  },
];

export default profiles;
